[코드 gsm 6-1] 넘파이 설치

In [1]:
!pip install numpy;

[코드 gsm 6-2] 1차원 배열 생성

In [2]:
import numpy as np

list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

a.shape:  (4,)
a[0]:  1


[코드 gsm 6-3] 2차원 배열 생성

In [3]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

b.shape:  (2, 3)
b[0,0]:  1
b[0]:  [1 2 3]


[코드 gsm 6-4] 2차원 배열 생성

In [4]:
import numpy as np

b = np.arange(4)
print('b.shape:\n ', b.shape)
print(b)

b.shape:
  (4,)
[0 1 2 3]


[코드 gsm 6-5] 배열 생성 함수

In [5]:
import numpy as np

a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[코드 gsm 6-6] 배열 생성 함수

In [6]:
import numpy as np

a = np.array([1, 2], dtype=np.float64)
print(a.dtype)
print('a\n', a)

a_i8 = a.astype(np.int8)
print(a_i8.dtype)
print('a_i8\n', a_i8)

float64
a
 [1. 2.]
int8
a_i8
 [1 2]


[코드 gsm 6-7] 배열의 속성 호출

In [7]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


[코드 gsm 6-8] 배열 모양 변경

In [8]:
a = np.arange(8)
print('a\n', a)

a.shape = (2,4)
print('shape\n', a)

print('flatten\n', a.flatten( ))

a.resize((4,2))
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


[코드 gsm 6-9] 행렬의 행과 열 교차

In [9]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose()
print('b\n', b)

c = a.T
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


[코드 gsm 6-10] 배열로 마스킹

In [10]:
import numpy as np

mask = np.array([0, 1], dtype=bool)

print(mask)

data = np.random.randn(2,1)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남
print('\n구승민_마스킹된 데이터 출력\n',data[mask])

[False  True]

data 출력
 [[ 0.49236123]
 [-2.0770142 ]]

구승민_마스킹된 데이터 출력
 [[-2.0770142]]


[코드 gsm 6-11] 조건식으로 마스킹

In [11]:
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)

양수 데이터 출력 
 [0.49236123]


[코드 gsm 6-12] 브로드캐스팅

In [12]:
import numpy as np

a = np.array([4])

b = np.array([1, 2,3])

result = a + b
print("\n브로드캐스팅된 결과:\n", result)


브로드캐스팅된 결과:
 [5 6 7]


[코드 gsm 6-13] 배열 복사

In [13]:
a = np.arange(6)
c = a.copy( )

c[0] = 20
print('A: ', a)
print('C: ', c)

A:  [0 1 2 3 4 5]
C:  [20  1  2  3  4  5]


[코드 gsm 6-14] 배열 정렬

In [14]:
a = np.array([3, 2, 5, 1, 4])

print('정렬 후\n',np.sort(a))
print('원본\n',a)

a.sort( )
print('원본변경\n',a)

정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
원본변경
 [1 2 3 4 5]


[코드 gsm 6-15] 리스트로 시리즈 생성

In [15]:
!pip install pandas;
import pandas as pd

a = pd.Series([7, 8])
print(a)
b = pd.Series([10, 11], index=['a', 'b'])
print(b)

0    7
1    8
dtype: int64
a    10
b    11
dtype: int64


[코드 gsm 6-16] 리스트로 데이터프레임 생성

In [16]:
list1 = list([['한빛', '남자'], ['한결', '남자']])
col_names = ['이름', '성별']
pd.DataFrame(list1, columns=col_names)

이름  성별
0  한빛  남자
1  한결  남자

[코드 gsm 6-17] 딕셔너리로 데이터프레임 생성

In [17]:
dict1 = {'이름':{0:'한빛', 1:'한결'}, '성별':{0:'남자', 1: '여자'}}
pd.DataFrame(dict1)

이름  성별
0  한빛  남자
1  한결  여자

[코드 gms 6-18] 배열로 데이터프레임 생성

In [18]:
import numpy as np

arr1 = np.array([['한빛','남자'], ['한결','여자']])

col_names = ['이름','성별']

pd.DataFrame(arr1, columns=col_names)

이름  성별
0  한빛  남자
1  한결  여자

[코드 gsm 6-19] 데이터프레임 생성

In [19]:
import numpy as np

list1 = list([['구승민','남자'], ['이가원','여자'], ['배규민','남자']])
col_names = ['이름','성별']
df = pd.DataFrame(list1, columns=col_names)
df

이름  성별
0  구승민  남자
1  이가원  여자
2  배규민  남자

[코드 gsm 6-20] 데이터프레임을 CSV 파일로 저장

In [20]:
df.to_csv('./gsm_seris.csv', header=True, index=False, encoding='utf-8')

df2 = pd.read_csv('./gsm_seris.csv', sep=',')

df2.columns

Index(['이름', '성별'], dtype='object')

[코드 gsm 6-21] 데이터프레임 값 개수와 빈도수 확인

In [21]:
df2.describe( )

이름  성별
count     3   3
unique    3   2
top     구승민  남자
freq      1   2

[코드 gsm 6-22] 데이터프레임의 처음 세 행 검색

In [22]:
df2.head()

이름  성별
0  구승민  남자
1  이가원  여자
2  배규민  남자

In [23]:
df2.tail(1)

이름  성별
2  배규민  남자

[코드 gsm 6-23] 열 기준으로 정렬
    

In [24]:
import numpy as np

df.sort_values(by=['이름'], ascending=False).head( )

이름  성별
1  이가원  여자
2  배규민  남자
0  구승민  남자

[코드 gsn 6-24] 열 이름으로 데이터 조회

In [25]:
df[['이름']].head( )

이름
0  구승민
1  이가원
2  배규민

[코드 gsm 6-25] 인덱스로 데이터 조회

In [26]:
df.iloc[1:2, 0:1]

이름
1  이가원

[코드 gsm 6-25] 인덱스로 데이터 조회

In [27]:
df.iloc[0:1, 0:1]

이름
0  구승민

[코드 gsm 6-26] 조건식을 만족하는 데이터 조회(1)

In [28]:
df[df['이름'] == '배규민'].head( )

이름  성별
2  배규민  남자

[코드 gsm 6-27] 조건식을 만족하는 데이터 조회(2)

In [29]:
list1 = list([['구승민', '남자', 23, 183],
['이가원', '여자', 24, 162],
['배규민', '남자', 23, 179],
['고고림', '남자', 21, 182]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)
df[df['키'] > 180]

이름  성별  나이    키
0  구승민  남자  23  183
3  고고림  남자  21  182

[코드 gsm 6-28] 두 조건식을 동시에 만족하는 데이터 조회

In [30]:
df[(df['성별'] == '여자') & (df['키'] > 160)]

이름  성별  나이    키
1  이가원  여자  24  162

[코드 gsm 6-29] 특정 문자열을 포함하는 문자열 데이터 조회

In [31]:
df[df['이름'].str.contains('고')]

이름  성별  나이    키
3  고고림  남자  21  182

[코드 gsm 6-30] 데이터프레임 통계 확인

In [32]:
df.describe()

나이           키
count   4.000000    4.000000
mean   22.750000  176.500000
std     1.258306    9.814955
min    21.000000  162.000000
25%    22.500000  174.750000
50%    23.000000  180.500000
75%    23.250000  182.250000
max    24.000000  183.000000

[코드 gsm 6-31] 인덱스로 조회한 데이터를 수정

In [33]:
df.loc[3,'키'] = df.loc[3,'키'] + 5
df.loc[[3]]

이름  성별  나이    키
3  고고림  남자  21  187

[코드 gsm 6-32] 반복 연산자 사용

In [34]:
df.loc[1:3,'키'] = ['모름'] * 3
df

<ipython-input-34-ff0e8639adba>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['모름', '모름', '모름']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[1:3,'키'] = ['모름'] * 3


이름  성별  나이    키
0  구승민  남자  23  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름
3  고고림  남자  21   모름

[코드 gsm 6-33] 열 생성

In [35]:
df['보너스'] = df['나이'] * 10000
df.head(3)

이름  성별  나이    키     보너스
0  구승민  남자  23  183  230000
1  이가원  여자  24   모름  240000
2  배규민  남자  23   모름  230000

[코드 gsm 6-34] 열 삭제

In [36]:
df.drop('보너스', axis=1, inplace=True)
df.head(3)

이름  성별  나이    키
0  구승민  남자  23  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름

[코드 gsm 6-35] 인덱스 변경(2)

In [37]:
df.reset_index(inplace=True)
df.head(3)

index   이름  성별  나이    키
0      0  구승민  남자  23  183
1      1  이가원  여자  24   모름
2      2  배규민  남자  23   모름

[코드 gsm 6-36] 데이터 치환

In [38]:
rep_cond = {'성별':{'남자':1, '여자':0}}
df2 = df.replace(rep_cond)
df2.head(3)

<ipython-input-38-b11e9d5f17ba>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2 = df.replace(rep_cond)


index   이름  성별  나이    키
0      0  구승민   1  23  183
1      1  이가원   0  24   모름
2      2  배규민   1  23   모름

[문제_gsm_6_1] 1차원 배열을 생성하고, 배열을 2차원으로 변환하려면 어떤 함수를 사용해야 하는가?

In [39]:
a = np.arange(6)
a = a.reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


[문제_gsm_6_2] 배열 a의 값을 복사하여 새로운 배열 b를 생성하려면 어떤 함수를 사용해야 하는가?

In [40]:
b = np.copy(a)
print(b)

[[0 1 2]
 [3 4 5]]


[문제_gsm_6_3] 배열을 1차원으로 평탄화(flatten)하려면 어떤 함수를 사용해야 하는가?

In [41]:
a = a.flatten()
print(a)

[0 1 2 3 4 5]


[문제_gsm_6_4] 배열을 정렬된 상태로 반환하되, 원본 배열은 유지하려면 어떤 함수를 사용해야 하는가?

In [42]:
sorted_a = np.sort(a)
print(sorted_a)

[0 1 2 3 4 5]


[문제_gsm_6_5] 배열의 크기를 3행 2열로 조정하려면 어떤 함수를 사용해야 하는가?

In [43]:
a.resize((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


[문제_gsm_6_6] 배열 a에서 dtype을 float으로 변환하려면 어떤 함수를 사용해야 하는가?

In [44]:
a = a.astype(np.float32)
print(a)

[[0. 1.]
 [2. 3.]
 [4. 5.]]


[문제_gsm_6_7] 모든 값이 0인 배열을 생성하려면 어떤 함수를 사용해야 하는가?

In [45]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


[문제_gsm_6_8] 모든 값이 1인 배열을 생성하려면 어떤 함수를 사용해야 하는가?

In [46]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


[문제_gsm_6_9] 아래 문제의 실행결과는?

In [47]:
mask = np.array([0, 1], dtype=bool)
data = np.array([[2, 3], [5, 6]])
print(data[mask])

[[5 6]]


[문제_gsm_6_10] 배열의 전치 행렬을 구하려면 어떤 속성을 사용해야 하는가?

In [48]:
print(a.T)

[1. 1. 1. 1. 1.]


[문제_gsm_6_11] 아래 문제의 실행결과는?

In [49]:
data = {'k': [2, 3], 'M': [5, 6]}
df3 = pd.DataFrame(data)
print(df3.iloc[0:1,])
print(df3.loc[0:1,])

   k  M
0  2  5
   k  M
0  2  5
1  3  6


[문제_gsm_6_12] 데이터프레임의 인덱스를 초기화하려면 어떤 함수를 사용해야 하는가?

In [50]:
df.reset_index(inplace=True)

[문제_gsm_6_13] 데이터프레임의 첫 두 행을 선택하려면 어떤 함수를 사용해야 하는가?


In [51]:
print(df.head(2))

   level_0  index   이름  성별  나이    키
0        0      0  구승민  남자  23  183
1        1      1  이가원  여자  24   모름


[문제_gsm_6_14] 배열에서 특정 조건을 만족하는 값을 필터링하려면 어떤 함수를 사용해야 하는가?

In [52]:
positive_values = a[a > 0]
print(positive_values)

[1. 1. 1. 1. 1.]


[문제_gsm_6_15] 데이터프레임에 새로운 열(‘연봉’)을 추가하려면 어떤 함수를 사용해야 하는가?

In [53]:
df['연봉'] = df['나이'] * 1000

[문제_gsm_6_16] 데이터프레임에서 특정 열을 삭제하려면 어떤 함수를 사용해야 하는가?

In [54]:
df.drop('나이', axis=1, inplace=True)
df

level_0  index   이름  성별    키     연봉
0        0      0  구승민  남자  183  23000
1        1      1  이가원  여자   모름  24000
2        2      2  배규민  남자   모름  23000
3        3      3  고고림  남자   모름  21000

[문제_gsm_6_17] 데이터프레임에서 특정 조건을 만족하는 행을 선택하려면 어떤 함수를 사용해야 하는가?

In [55]:
list1 = list([['구승민', '남자', 23, 183],
['이가원', '여자', 24, 162],
['배규민', '남자', 23, 179],
['고고림', '남자', 21, 182]])
col_names = ['이름', '성별', '나이', '키']
df = pd.DataFrame(list1, columns=col_names)

In [56]:
filtered_df = df[(df['성별'] == '여자') & (df['키'] > 160)]
print(filtered_df)

    이름  성별  나이    키
1  이가원  여자  24  162


[문제_gsm_6_18] 데이터프레임에서 특정 열(‘이름’)만 선택하려면 어떤 값을 넣어야 하는가?

In [57]:
df['이름']

0    구승민
1    이가원
2    배규민
3    고고림
Name: 이름, dtype: object